### ISSUE TITLE
Rack responses not being processed correctly by gateway when deployed

### ISSUE THREAD

**Issue by travisoneill** [travisoneill/algo-arena-v2#3]
No issue locally.  Maybe a python 3.5 vs 3.4 issue?

**Comment by travisoneill** [comment]
Potentially an encoding issue.  Try `application/json` header in rack app.  

```
Traceback (most recent call last):
  File "/home/travis_h_oneill/src/algorithm-arena/default/gateway/env/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/travis_h_oneill/src/algorithm-arena/default/gateway/env/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/travis_h_oneill/src/algorithm-arena/default/gateway/env/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/travis_h_oneill/src/algorithm-arena/default/gateway/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/travis_h_oneill/src/algorithm-arena/default/gateway/env/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/travis_h_oneill/src/algorithm-arena/default/gateway/env/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/travis_h_oneill/src/algorithm-arena/default/gateway/api_gateway.py", line 41, in send
    final_data[key] =  json.loads(res.content)
  File "/home/travis_h_oneill/src/algorithm-arena/default/gateway/env/lib/python3.4/site-packages/flask/json.py", line 149, in loads
    return _json.loads(s, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 331, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```
